"use client";
//import type { Metadata } from 'next'
import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import AppHeader from "@/components/appHeader";
import Sidebar from "@/components/sidebar";
import Container from "react-bootstrap/Container";
import useRole from "@/hooks/useRole";
import React from "react";
import { AuthProvider } from "@/contexts/AuthContext";
//import './globals.css'

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // React.useEffect(() => {
  //   // Update the currentRole state whenever the role changes using the useRole hook
  //   const handleRoleChange = () => {
  //     setCurrentRole(useRole());
  //   };

  //   // Add event listener for storage changes (if not already implemented in useRole)
  //   window.addEventListener("storage", handleRoleChange);

  //   return () => {
  //     window.removeEventListener("storage", handleRoleChange);
  //   };
  // }, []);
  return (
    <AuthProvider>
      <html key={0} lang="en" style={{ height: "100%" }}>
        <body key={1} className={inter.className} style={{ height: "100%" }}>
          <div key={2} className="app-wrapper">
            <AppHeader />
            <div className="flex flex-1 main-content">
              <Sidebar />
              <Container>{children}</Container>
            </div>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
